name: Extract Quantities from IFC

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.ifc'
      - 'extract_quantities.py'

jobs:
  run-extraction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install ifcopenshell

      - name: List IFC files
        run: ls -l *.ifc

      - name: Run extraction script for all IFC files
        run: python extract_quantities.py
        env:
          PYTHONUNBUFFERED: 1

      - name: List output files
        run: ls -l reports

      - name: Upload extracted reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extracted-reports
          path: reports/*
